// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiArticleHealthData, GetApiArticleHealthResponses, GetHealthData, GetHealthResponses, PostApiArticleGenerateData, PostApiArticleGenerateErrors, PostApiArticleGenerateResponses, PostApiAuthSecretData, PostApiAuthSecretErrors, PostApiAuthSecretResponses, PostApiImageEditData, PostApiImageEditErrors, PostApiImageEditResponses, PostApiImageGenerateData, PostApiImageGenerateErrors, PostApiImageGenerateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Check Server Health
 *
 * This endpoint checks whether the server is running properly.
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Generate Image via AI
 *
 * This endpoint sends prompt instructions to browser automation to create images.
 */
export const postApiImageGenerate = <ThrowOnError extends boolean = false>(options?: Options<PostApiImageGenerateData, ThrowOnError>) => (options?.client ?? client).post<PostApiImageGenerateResponses, PostApiImageGenerateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/image/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Edit Image via AI
 *
 * This endpoint sends prompt instructions to browser automation to edit images.
 */
export const postApiImageEdit = <ThrowOnError extends boolean = false>(options?: Options<PostApiImageEditData, ThrowOnError>) => (options?.client ?? client).post<PostApiImageEditResponses, PostApiImageEditErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/image/edit',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});

/**
 * Generate Access Token (JWT)
 *
 * Exchange the Master API Key and Email with a JWT Token to access other endpoints.
 */
export const postApiAuthSecret = <ThrowOnError extends boolean = false>(options?: Options<PostApiAuthSecretData, ThrowOnError>) => (options?.client ?? client).post<PostApiAuthSecretResponses, PostApiAuthSecretErrors, ThrowOnError>({
    url: '/api/auth/secret',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Check Article Service Health
 *
 * This endpoint checks the health status of the Article Service.
 */
export const getApiArticleHealth = <ThrowOnError extends boolean = false>(options?: Options<GetApiArticleHealthData, ThrowOnError>) => (options?.client ?? client).get<GetApiArticleHealthResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/article/health',
    ...options
});

/**
 * Generate Article via AI
 *
 * This endpoint validates the input using Zod and sends a task to RabbitMQ.
 */
export const postApiArticleGenerate = <ThrowOnError extends boolean = false>(options?: Options<PostApiArticleGenerateData, ThrowOnError>) => (options?.client ?? client).post<PostApiArticleGenerateResponses, PostApiArticleGenerateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/article/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});
