// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetHealthResponses, PostApiArticleGenerateData, PostApiArticleGenerateErrors, PostApiArticleGenerateResponses, PostApiImageGenerateData, PostApiImageGenerateErrors, PostApiImageGenerateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Cek Kesehatan Server
 *
 * Endpoint ini memeriksa apakah server berjalan dengan baik.
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Generate Gambar via AI
 *
 * Endpoint ini mengirim instruksi prompt ke browser automation untuk membuat gambar.
 */
export const postApiImageGenerate = <ThrowOnError extends boolean = false>(options: Options<PostApiImageGenerateData, ThrowOnError>) => (options.client ?? client).post<PostApiImageGenerateResponses, PostApiImageGenerateErrors, ThrowOnError>({
    url: '/api/image/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate Artikel via AI
 *
 * Endpoint ini memvalidasi input menggunakan Zod dan mengirim task ke RabbitMQ.
 */
export const postApiArticleGenerate = <ThrowOnError extends boolean = false>(options: Options<PostApiArticleGenerateData, ThrowOnError>) => (options.client ?? client).post<PostApiArticleGenerateResponses, PostApiArticleGenerateErrors, ThrowOnError>({
    url: '/api/article/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
