// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://scraper.misbakhul.my.id' | (string & {});
};

export type WebhookResponse = {
    type: string;
    status: WebHookStatus;
    error?: string;
    topic?: string;
    title?: string;
    content?: string;
    /**
     * Data tambahan untuk artikel
     */
    articleData?: {
        /**
         * ID Artikel di Database
         */
        id?: string;
    };
};

export type WebHookStatus = 'pending' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';

export type WebHookStatus2 = 'pending' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';

export type ImageRequest = {
    /**
     * Deskripsi detail gambar yang ingin dibuat
     */
    prompt: string;
    /**
     * Gaya Gambar
     */
    tone?: 'artSchool' | 'doodle' | 'popArt' | 'dramatic' | 'neonPunk' | 'ghibli' | 'corporateFlat' | 'manga' | 'clay3d' | 'vintageFilm';
    /**
     * Rasio Aspek Gambar
     */
    aspectRatio?: '1:1' | '16:9' | '9:16' | '21:9' | '4:3';
    /**
     * URL Callback untuk menerima hasil (URL Gambar/Path)
     */
    webhookUrl?: string;
    /**
     * Apakah format gambar harus dalam format WebP?
     */
    webpFormat?: boolean;
    /**
     * Ukuran maksimum gambar dalam KB (100 KB default)
     */
    imageMaxSizeKB?: number;
    /**
     * Data tambahan untuk artikel
     */
    articleData?: {
        /**
         * ID Artikel di Database
         */
        id?: string;
        imageIndex: number;
    };
};

export type SuccessImageResponse = {
    success: boolean;
    message: string;
    data: {
        prompt: string;
        status: 'pending' | 'queued' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';
        webhookUrl?: string;
    };
};

export type ImageWebhookResponse = {
    type: string;
    status: string;
    error?: string;
    imagePath: string;
    /**
     * Data tambahan untuk artikel
     */
    articleData?: {
        /**
         * ID Artikel di Database
         */
        id?: string;
        imageIndex: number;
    };
};

export type ArticleRequest = {
    /**
     * Topik utama artikel
     */
    topic: string;
    /**
     * List keyword SEO
     */
    keywords?: Array<string>;
    /**
     * Kategori Artikel
     */
    category?: string;
    /**
     * Gaya Bahasa
     */
    tone?: 'professional' | 'educational' | 'journalist' | 'genZ' | 'mythBuster' | 'visionary' | 'directResponse';
    /**
     * URL Callback
     */
    webhookUrl?: string;
    /**
     * Jumlah gambar yang diinginkan
     */
    imageCount?: number;
    /**
     * Data tambahan untuk artikel
     */
    articleData?: {
        /**
         * ID Artikel di Database
         */
        id?: string;
    };
};

export type SuccessArticleResponse = {
    success: boolean;
    message: string;
    data: {
        status: 'pending' | 'queued' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';
        /**
         * URL Callback
         */
        webhookUrl?: string;
        /**
         * Data tambahan untuk artikel
         */
        articleData?: {
            /**
             * ID Artikel di Database
             */
            id?: string;
        };
    };
};

export type ArticleWebhookResponse = {
    type?: string;
    topic: string;
    title: string;
    content: string;
    /**
     * Data tambahan untuk artikel
     */
    articleData?: {
        /**
         * ID Artikel di Database
         */
        id?: string;
    };
    status: 'pending' | 'queued' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';
    /**
     * Metadata tambahan untuk pemrosesan gambar
     */
    properties?: {
        imageCount?: number;
        /**
         * Daftar prompt gambar hasil ekstraksi AI
         */
        imagePrompts?: Array<{
            index: number;
            tone: 'artSchool' | 'doodle' | 'popArt' | 'dramatic' | 'neonPunk' | 'ghibli' | 'corporateFlat' | 'manga' | 'clay3d' | 'vintageFilm';
            prompt: string;
        }>;
    };
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Server Berjalan dengan Baik
     */
    200: {
        success: 'true';
        message?: string;
        timestamp?: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostApiImageGenerateData = {
    body?: ImageRequest;
    headers: {
        /**
         * API Key untuk autentikasi
         */
        'x-api-key': string;
    };
    path?: never;
    query?: never;
    url: '/api/image/generate';
};

export type PostApiImageGenerateErrors = {
    /**
     * Validasi Gagal
     */
    400: {
        error: string;
    };
};

export type PostApiImageGenerateError = PostApiImageGenerateErrors[keyof PostApiImageGenerateErrors];

export type PostApiImageGenerateResponses = {
    /**
     * Request diterima dan masuk antrian
     */
    202: SuccessImageResponse;
};

export type PostApiImageGenerateResponse = PostApiImageGenerateResponses[keyof PostApiImageGenerateResponses];

export type PostApiArticleGenerateData = {
    body?: ArticleRequest;
    headers: {
        /**
         * API Key untuk autentikasi
         */
        'x-api-key': string;
    };
    path?: never;
    query?: never;
    url: '/api/article/generate';
};

export type PostApiArticleGenerateErrors = {
    /**
     * Validasi Gagal
     */
    400: {
        error: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: boolean;
        error: string;
        data: {
            status: 'pending' | 'queued' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';
        };
    };
};

export type PostApiArticleGenerateError = PostApiArticleGenerateErrors[keyof PostApiArticleGenerateErrors];

export type PostApiArticleGenerateResponses = {
    /**
     * Request diterima dan masuk antrian
     */
    202: SuccessArticleResponse;
};

export type PostApiArticleGenerateResponse = PostApiArticleGenerateResponses[keyof PostApiArticleGenerateResponses];
