// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

export type WebhookResponse = {
    type: string;
    status: WebHookStatus;
    error?: string;
    topic?: string;
    title?: string;
    content?: string;
    /**
     * Additional article data
     */
    articleData?: {
        /**
         * Article ID in Database
         */
        id?: string;
    };
};

export type WebHookStatus = 'pending' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';

export type WebHookStatus2 = 'pending' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';

export type ImageRequest = {
    /**
     * Deskripsi detail gambar yang ingin dibuat
     */
    prompt: string;
    /**
     * Gaya Gambar
     */
    tone?: 'artSchool' | 'doodle' | 'popArt' | 'dramatic' | 'neonPunk' | 'ghibli' | 'corporateFlat' | 'manga' | 'clay3d' | 'vintageFilm' | 'realisticPhoto' | 'graphicDesign' | 'cinematic' | 'eventPhoto' | 'pixelArt' | 'oilPainting' | 'isometric3d';
    /**
     * Rasio Aspek Gambar
     */
    aspectRatio?: '1:1' | '16:9' | '9:16' | '21:9' | '4:3' | '4:5' | '3:4' | '3:2' | '2:3' | '16:10' | '2.35:1';
    /**
     * URL Callback untuk menerima hasil (URL Gambar/Path)
     */
    webhookUrl?: string;
    /**
     * Apakah format gambar harus dalam format WebP?
     */
    webpFormat?: boolean;
    /**
     * Ukuran maksimum gambar dalam KB (100 KB default)
     */
    imageMaxSizeKB?: number;
    /**
     * Data tambahan untuk artikel
     */
    articleData?: {
        /**
         * ID Artikel di Database
         */
        id?: string;
        imageIndex?: number;
    };
};

export type EditImageRequest = {
    /**
     * Instruksi edit gambar
     */
    prompt: string;
    tone?: 'artSchool' | 'doodle' | 'popArt' | 'dramatic' | 'neonPunk' | 'ghibli' | 'corporateFlat' | 'manga' | 'clay3d' | 'vintageFilm' | 'realisticPhoto' | 'graphicDesign' | 'cinematic' | 'eventPhoto' | 'pixelArt' | 'oilPainting' | 'isometric3d';
    aspectRatio?: '1:1' | '16:9' | '9:16' | '21:9' | '4:3' | '4:5' | '3:4' | '3:2' | '2:3' | '16:10' | '2.35:1';
    webhookUrl?: string;
    webpFormat?: boolean | null;
    imageMaxSizeKB?: number | null;
    articleData?: {
        id?: string;
        imageIndex?: number | null;
    };
    /**
     * File gambar input
     */
    image: Blob | File;
};

export type SuccessImageResponse = {
    success: boolean;
    message: string;
    data: {
        queue: number;
        prompt: string;
        status: 'pending' | 'queued' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';
        webhookUrl?: string;
    };
};

export type ImageWebhookResponse = {
    type: string;
    status: string;
    error?: string;
    imagePath: string;
    /**
     * Data tambahan untuk artikel
     */
    articleData?: {
        /**
         * ID Artikel di Database
         */
        id?: string;
        imageIndex?: number;
    };
};

export type GenerateSecretRequest = {
    /**
     * User email to be embedded in the token
     */
    email: string;
};

export type GenerateSecretResponse = {
    success: boolean;
    /**
     * Generated JWT Token
     */
    token: string;
    /**
     * Token expiration time
     */
    expiresIn: string;
};

export type ArticleRequest = {
    /**
     * Main topic of the article
     */
    topic: string;
    /**
     * List of SEO keywords
     */
    keywords?: Array<string>;
    /**
     * Article category
     */
    category?: string;
    /**
     * Article tone
     */
    tone?: 'professional' | 'educational' | 'journalist' | 'genZ' | 'mythBuster' | 'visionary' | 'directResponse';
    /**
     * Callback URL
     */
    webhookUrl?: string;
    /**
     * Number of images to generate
     */
    imageCount?: number;
    /**
     * Additional article data
     */
    articleData?: {
        /**
         * Article ID in Database
         */
        id?: string;
    };
};

export type SuccessArticleResponse = {
    success: boolean;
    message: string;
    data: {
        status: 'pending' | 'queued' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';
        /**
         * URL Callback
         */
        webhookUrl?: string;
        /**
         * Additional article data
         */
        articleData?: {
            /**
             * Article ID in Database
             */
            id?: string;
        };
    };
};

export type ArticleWebhookResponse = {
    type?: string;
    topic: string;
    title: string;
    content: string;
    /**
     * Additional article data
     */
    articleData?: {
        /**
         * Article ID in Database
         */
        id?: string;
    };
    status: 'pending' | 'queued' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';
    /**
     * Additional metadata for image processing
     */
    properties?: {
        imageCount?: number;
        /**
         * List of image prompts for AI-generated images
         */
        imagePrompts?: Array<{
            index: number;
            tone: 'artSchool' | 'doodle' | 'popArt' | 'dramatic' | 'neonPunk' | 'ghibli' | 'corporateFlat' | 'manga' | 'clay3d' | 'vintageFilm' | 'realisticPhoto' | 'graphicDesign' | 'cinematic' | 'eventPhoto' | 'pixelArt' | 'oilPainting' | 'isometric3d';
            prompt: string;
        }>;
    };
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Server is running properly
     */
    200: {
        success: 'true';
        message?: string;
        timestamp?: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostApiImageGenerateData = {
    body?: ImageRequest;
    path?: never;
    query?: never;
    url: '/api/image/generate';
};

export type PostApiImageGenerateErrors = {
    /**
     * Validation Failed
     */
    400: {
        error: string;
    };
};

export type PostApiImageGenerateError = PostApiImageGenerateErrors[keyof PostApiImageGenerateErrors];

export type PostApiImageGenerateResponses = {
    /**
     * Request accepted and queued for processing
     */
    202: SuccessImageResponse;
};

export type PostApiImageGenerateResponse = PostApiImageGenerateResponses[keyof PostApiImageGenerateResponses];

export type PostApiImageEditData = {
    body?: EditImageRequest;
    path?: never;
    query?: never;
    url: '/api/image/edit';
};

export type PostApiImageEditErrors = {
    /**
     * Validation Failed
     */
    400: {
        error: string;
    };
};

export type PostApiImageEditError = PostApiImageEditErrors[keyof PostApiImageEditErrors];

export type PostApiImageEditResponses = {
    /**
     * Request accepted and queued for processing
     */
    202: SuccessImageResponse;
};

export type PostApiImageEditResponse = PostApiImageEditResponses[keyof PostApiImageEditResponses];

export type PostApiAuthSecretData = {
    body?: GenerateSecretRequest;
    path?: never;
    query?: never;
    url: '/api/auth/secret';
};

export type PostApiAuthSecretErrors = {
    /**
     * Input Validation Failed
     */
    400: {
        success: boolean;
        error?: unknown;
    };
    /**
     * Invalid Master API Key
     */
    401: {
        success: boolean;
        error: string;
    };
};

export type PostApiAuthSecretError = PostApiAuthSecretErrors[keyof PostApiAuthSecretErrors];

export type PostApiAuthSecretResponses = {
    /**
     * Successfully created token
     */
    200: GenerateSecretResponse;
};

export type PostApiAuthSecretResponse = PostApiAuthSecretResponses[keyof PostApiAuthSecretResponses];

export type GetApiArticleHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/article/health';
};

export type GetApiArticleHealthResponses = {
    /**
     * Article Service is healthy
     */
    200: {
        success: boolean;
        message: string;
    };
};

export type GetApiArticleHealthResponse = GetApiArticleHealthResponses[keyof GetApiArticleHealthResponses];

export type PostApiArticleGenerateData = {
    body?: ArticleRequest;
    path?: never;
    query?: never;
    url: '/api/article/generate';
};

export type PostApiArticleGenerateErrors = {
    /**
     * Validation Failed
     */
    400: {
        error: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        success: boolean;
        error: string;
        data: {
            status: 'pending' | 'queued' | 'generating' | 'waiting_for_images' | 'completed' | 'failed_content' | 'failed_images' | 'failed' | 'draft' | 'published';
        };
    };
};

export type PostApiArticleGenerateError = PostApiArticleGenerateErrors[keyof PostApiArticleGenerateErrors];

export type PostApiArticleGenerateResponses = {
    /**
     * Request accepted and added to queue
     */
    202: SuccessArticleResponse;
};

export type PostApiArticleGenerateResponse = PostApiArticleGenerateResponses[keyof PostApiArticleGenerateResponses];
