import { ColorSchemeScript, Container, mantineHtmlProps } from '@mantine/core';
import '@mantine/core/styles.css';
import type { Metadata } from "next";
import { Yusei_Magic } from "next/font/google";
import "./globals.css";
import { Providers } from './provider';

const yuseiMagic = Yusei_Magic({
  variable: "--font-yusei-magic",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${yuseiMagic.variable} antialiased`}>
        <Providers>
            <Container 
              size="xs" 
              px={0} 
              style={{ 
                height: "100dvh", 
                overflowY: "auto",
                display: "flex",
                flexDirection: "column"
              }}
              className='container_utm'
            >
              {children}
            </Container>
        </Providers>
      </body>
    </html>
  );
}